### ISSUE TITLE
Impersonation Support?

### ISSUE THREAD

**Issue by tedleman** [maropu/spark-sql-server#18]
Hi,

We're looking pretty seriously at using this as a spark sql postgres interface for users to connect to from BI tools over JDBC/ODBC. 

I see that this project supports kerberos authentication, which is excellent. However, any hive queries will need to be run as the end user's principal. Is this currently possible if the server is started by a different user principal?

For example:

User A (Service principal) starts the server. User B connects to the server. When User B runs a query, does spark-sql-server send the query to hive on behalf of user B?

**Comment by maropu** [comment]
Thanks for the comment! I'll check later.

**Comment by maropu** [comment]
I'm working on https://github.com/maropu/spark-sql-server/tree/ImpersonationSpike

**Comment by maropu** [comment]
Some references:
 - User impersonation in Apache Spark 1.6 Thrift Server, https://community.hortonworks.com/articles/101418/user-impersonation-in-apache-spark-16-thrift-serve.html
 - Kerberos Concepts - Principals, Keytabs and Delegation Tokens, https://www.cloudera.com/documentation/enterprise/5-8-x/topics/cm_sg_principal_keytab.html

**Comment by maropu** [comment]
ISTM we could use Apache Livy to manage multiple `SQLContext`: https://livy.incubator.apache.org/

**Comment by tedleman** [comment]
@maropu Thanks!

**Comment by maropu** [comment]
I tried to transport port the Livy impersonation logic into the SQL server in https://github.com/maropu/spark-sql-server/commit/b9b882db7178c33583717a4b045970a1ec90c641.
Next, I'll check if this work correctly in days.

Usage:
```
./sbin/start-sql-server.sh \
  --conf spark.sql.server.executionMode=multi-context \
  --conf spark.yarn.keytab=keytabFile \
  --conf spark.yarn.principal=principal \
  --conf spark.yarn.impersonation.enabled=true
```
Then, the JDBC url is `jdbc:postgresql://[host]/[databaseName]?user=[proxyUser]`.

**Comment by weiatwork** [comment]
Hi @maropu I find your work via google.. Great work! Do you have any plan or do you think it is feasible to implement the support natively in Spark? It looks like right now Spark Thrift server lacks impersonation support.

**Comment by maropu** [comment]
Hi, weiatwork
What do u mean "natively"? Yea, I know the Spark Thrift one doesn't support that, so I'm working on this. BTW, it seems the HDP Spark thrift server support that (I don't try though...)

**Comment by weiatwork** [comment]
Oh I see. Thanks for your reply. The impersonation is definitely a deal-breaker for Spark, otherwise it's hard to run Thrift server in a shared environment..

HDP 1.x seems to have this support, but I'm not sure about HDP 2.x. Looks like this area is not well documented.

**Comment by maropu** [comment]
@weiatwork It seems HDP 2.x supports the impersonation and you should read https://community.hortonworks.com/articles/101418/user-impersonation-in-apache-spark-16-thrift-serve.html

**Comment by weiatwork** [comment]
Thanks for the pointer. It looks like even HDP 2.x only supports Spark 1.x for impersonation. No support for Spark 2.x yet.

**Comment by maropu** [comment]
As an initial prototype (see https://github.com/maropu/spark-sql-server/commit/7352eb6c0aaeba16f2db2fe040b4c22a1b7f04e8), I  finished implementing the impersonation based on Apache Livy. So, I'll close this ticket for now. If some bugs found (I thinks there are many bugs now), I'd be great if you report this issue tracker.
